#!/bin/bash

# Run triggers only on updates
if [ ! -e "/usr/local/skynet/data/users/admin" ]; then
	exit
fi

# Create a new Backup folder
skynet_BACKUP="/root/hst_nginx_backups/$(date +%d%m%Y%H%M)"
mkdir -p skynet_BACKUP

# Create a backup of the current configuration
cp -r /usr/local/skynet/nginx/conf/nginx.conf $SKYNET_BACKUP/nginx.conf

exit
