#!/bin/bash

# skynet Control Panel upgrade script for target version 1.3.3

#######################################################################################
#######                      Place additional commands below.                   #######
#######################################################################################

# Check if keys folder exists and adjust permissions
if [ -d "$SKYNET/data/keys" ]; then
	echo '[ * ] Update permissions'
	chmod 750 "$SKYNET/data/keys"
	chown admin:root "$SKYNET/data/keys"
fi

if [[ ! -e /etc/skynetcp/skynet.conf ]]; then
	echo '[ * ] Create global skynet config'

	mkdir -p /etc/skynetcp
	echo -e "# Do not edit this file, will get overwritten on next upgrade, use /etc/skynetcp/local.conf instead\n\nexport skynet='/usr/local/skynet'\n\n[[ -f /etc/skynetcp/local.conf ]] && source /etc/skynetcp/local.conf" > /etc/skynetcp/skynet.conf
fi
